### ISSUE TITLE
How can I use the DragSortAdapter with List<String>?

### ISSUE THREAD

**Issue by Chenng** [vinc3m1/DragSortAdapter#11]
I have tried the demo and everything goes fine.However when I change List<Integer> to List<String> it will crash if I drag the item.I thought it might be caused by ``getItemId`` because I only change this method when changing from List<Integer> to List<String> as data.
I wonder how to do it with String data.Thank you very much.

**Comment by vinc3m1** [comment]
You need a way to represent `String` as `long` in `getItemId()` yes. `.hashCode()` is a quick and dirty option.

**Comment by Chenng** [comment]
Thank  you .But I have tried
 ``  @Override public long getItemId(int position) { return (stringList.get(position)+position).hashCode();
    }`` 
or
 ``
  @Override public long getItemId(int position) {
        return stringList.get(position).hashCode();
    }``
it also caused this error.

**Comment by Chenng** [comment]
Also it is dirty as you said,but it do not take effect when I only change these in the demo.
I hope you could help me about this issue.
Thank you very much.
